### ISSUE TITLE
Feedback on workshop content

### ISSUE THREAD

**Issue by lehmus** [microsoft/MCW-ML-Ops#11]
Hi, I have some feedback related to the workshop content. I couldn't find any other channel to give feedback, so I decided to create an issue.

1. I think the workshop is missing the central piece of Azure MLOps, that is the Azure DevOps ML extension. The ML extension allows to trigger pipelines after a model has been updated in the Azure ML Workspace, but this feature has not been used in this workshop. Azure ML Workspace is only used to hold the model, but only for recording purposes. This created some confusion among workshop participants.

2. The ONNX model is discussed in the Whiteboard session and it is promised that we will "observe how this simplifies inference runtime code, enabling pluggability of different models and targeting a broad range of runtime environments and most importantly, improves inferencing speed over the native model". However, the Notebooks do not refer to ONNX or use the ONNX runtime. How is the use of ONNX demonstrated during the workshop? Does AML Workspace store the models in ONNX format, out of the box?

Otherwise I like the workshop content, thanks for good work! :)

**Comment by ciprianjichici** [comment]
Thank you @lehmus for the suggestions.

1. The approach of the workshop is centered around Azure DevOps as the main process orchestrator. Since the Azure DevOps build pipeline eventually leads to the model being (potentially) updated in AML,  the two scenarios (release triggered by build artifacts and release triggered by Azure DevOps ML extension) are practically equivalent. We are considering switching from the existing trigger to the Azure DevOps ML extension trigger in the next round of scheduled content updates.

2. The ONNX discussion was initially intended to be an exploratory one in the Whiteboard Design Session. We're making this a bit more clear in the November content update. We are also considering adding ONNX export and import to the technical solution in the next scheduled content update. Regarding your question about AML storing models in ONNX out of the box, the answer is no. AML stores models in whatever format results from the training process. To have a model stored as ONNX you must explicitly export it to this format after training.

**Comment by DawnmarieDesJardins** [comment]
Closing open issue with Nov 2019 update.
