### ISSUE TITLE
March 2020 – content update

### ISSUE THREAD

**Issue by timahenning** [microsoft/MCW-ML-Ops#18]
Suggestion content goes here

**Comment by shirolkar** [comment]
Suggestions for March 2020 updates:

1. Update the lab to use Compute Instances in Azure Machine Learning workspace instead of using Azure Notebooks.
2. Update all the affected UIs in Azure ML studio, Azure DevOps, and Application Insights sections.
3. Clean up instructions and errors / warnings in notebooks.
4. Bring install_requirements.sh up to date (azure-cli version).
5. Introduce the AML Datasets to version datasets stored in blob storage. Use the registered dataset in model training. 
6. Enhance the deep learning model deployment to accept original text documents as input instead of pre-processed word indices as input. This will help users in improved understanding and readability of both model performance (Exercise 7) and the data collected by applications insight telemetry (Exercise 8).
7. Update the WDS section to reflect all the changes.
