### ISSUE TITLE
Build pipeline fails while creating image

### ISSUE THREAD

**Issue by rgknp** [microsoft/MCW-ML-Ops#29]
Followed instructions but Azure Pipeline fails in Master Pipeline activity while creating Model Image. Log attached.[
[build.log](https://github.com/microsoft/MCW-ML-Ops/files/5054428/build.log)
](url)

**Comment by ErnstRoell** [comment]
Tried to run the Master Pipeline and ran into the same problem.

**Comment by shirolkar** [comment]
@rgknp  @ErnstRoell  @timahenning 
I am still investigating this issue. My independent test shows that this specific is resolved with azureml sdk verion 1.12.0. However, the build pipeline is failing because of another error with v 1.12.0. There is an error in the master pipeline at the end of train step: ServiceError: Failed to upload outputs due to Object reference not set to an instance of an object. This appears to be related to a fix done in v 1.12.0 in azureml-pipeline-core (https://docs.microsoft.com/en-us/azure/machine-learning/azure-machine-learning-release-notes). So the pipeline now fails even before it gets to image creation. In the Sept update we will convert to use Environments instead of the deprecated image creation.

**Comment by shirolkar** [comment]
@rgknp @ErnstRoell @timahenning  This issue should be fixed now. Please test with a new azure devops project that will install the latest SDK. Confirm that you are using Azure Machine Learning SDK version: 1.13.0.

**Comment by timahenning** [comment]
Closing the issue.  Solution provided.  We will be happy to reopen the issue if needed.
