### ISSUE TITLE
September 2020 Updates

### ISSUE THREAD

**Issue by timahenning** [microsoft/MCW-ML-Ops#30]

**Comment by shirolkar** [comment]
1. Update all the affected UIs in Azure ML studio, Azure DevOps, and Application Insights sections.
2. Fix open issues #28 and #29.
3. Update to use software environments instead of container images.
4. Reorganize train and evaluate steps so that (1) model is registered after it passes the evaluation step and (2) the creation and registration of environment is moved to the release pipeline during deployment.
5. Introduce the use of the Machine Learning extension for Azure DevOps (https://marketplace.visualstudio.com/items?itemName=ms-air-aiagility.vss-services-azureml) to trigger the release pipeline after model registration. Thus, the release pipeline is invoked only if the model evaluation is successful. 
6. Accountability is a key aspect of the Responbile ML development. Demonstrate the documentation of the machine learning lifecycle with datasheets.
7. Bring install_requirements.sh up to date (azure-ml-sdk and azure-cli versions).
8. Update the WDS section to reflect all the changes.

**Comment by jpe316** [comment]
- Examples should use ScriptRunConfig as estimators are being deprecated
- Specify input data as FileDataset
- example should use mlflow log model, read model for the tensorflow model
- example should use mlflow model deploy

tagging @akshaya-a / @mx-iao / @shivp950

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #36
