### ISSUE TITLE
Sept 2021 Update Suggestions

### ISSUE THREAD

**Issue by timahenning** [microsoft/MCW-ML-Ops#46]

**Comment by shirolkar** [comment]
1. Update all the affected UIs in Azure ML studio, Azure DevOps, and Application Insights sections.
2. Update the lab to use self-hosted agents: 
    - Provide step-by-step instructions as to how to create, configure and use self-hosted agents in Azure DevOps build and release pipelines
   - The pipelines continue to use azure-cli ML extension for MLOps (the self-hosted agents should support this extension)
3. Introduce Git Actions to trigger Azure pipelines. Step-by-step instructions for:
   - Creating a new private GitHub repo and cloning an existing lab repo
   - Authorize and install Azure pipelines with GitHub
   - Setup authentication with Azure DevOps using PAT
   - Create a GitHub workflow that triggers the Azure pipeline
4. Fix all open issues .
5. Bring install_requirements.sh up to date (azure-ml-sdk and azure-cli versions).
6. Update the WDS section to reflect all the changes.

**Comment by lostmygithubaccount** [comment]
using the v1 or v2 CLI extension for ML?

**Comment by shirolkar** [comment]
@lostmygithubaccount Hi Cody - we will upgrade to use the v2 of the CLI ML extension. Thanks. Jitendra

**Comment by shirolkar** [comment]
@DawnmarieDesJardins  @timahenning 
Based on the feedback from SMEs, we will not add git actions as they are not relevant for this lab. Instead we will provide instructions for setup and related build assets / code for both self-hosted agents and Microsoft-hosted free agents. Based on other feedback from SMEs, we will look to shorten the exercises, and possibly make some exercises optional.

**Comment by shirolkar** [comment]
@DawnmarieDesJardins @timahenning @lostmygithubaccount I had to completely rework the build pipeline so that it can run on both Self-hosted agent and Microsoft hosted agents with minimal setup and configuration. Thus, the underlying repo source code (https://github.com/solliancenet/mcw-mlops-starter-v3) will be significantly changed. Please note that we will plan to use CLI v2 when we have updated support for running ML pipelines, expected in October 2021, as part of future MCW update/refresh.

**Comment by DawnmarieDesJardins** [comment]
Closing issue with merge of PR #49
