### ISSUE TITLE
Test data prediction:  name 'inputs_dc' is not defined

### ISSUE THREAD

**Issue by lehmus** [microsoft/MCW-ML-Ops#9]
In Exercise 6, Task 4, the script is not able to find test data:
![Task 4](https://user-images.githubusercontent.com/16114036/67813636-b0da6d80-faaa-11e9-8219-04d4b84a6e6e.png)

Similarly, in Exercise 7, the Test Deployment notebook gives a similar message:
![Notebook output](https://user-images.githubusercontent.com/16114036/67813917-6b6a7000-faab-11e9-82b3-be1d765aecad.png)

Any idea how to fix this? It's not an error per se, since the release pipeline completes successfully and the notebook does not throw an exception here.

**Comment by timahenning** [comment]
Thank you for reporting this issue.  Please take a moment to review the help and support guidance.  https://microsoftcloudworkshop.com/  We will review your issue soon.

Tim

**Comment by dficarel** [comment]
I am having the same issue as @lehmus.  Is there any resolution for this yet?

**Comment by timahenning** [comment]
We are actively working on this issue.

Tim

**Comment by shirolkar** [comment]
@lehmus @dficarel @DawnmarieDesJardins @timahenning @ciprianjichici 

Thanks for reporting the issue. 

This issue is fixed. To get the fix, you have to get the latest score.py file from https://github.com/solliancenet/mcw-mlops-starter. Copy the new score.py file in your repo’s script folder. The other option is if you redo the lab, the repo import will now pickup the latest file.

This issue happened because of API change for the ModelDataCollector class with the latest Azure ML Python SDK.

Thanks.
Jitendra

**Comment by timahenning** [comment]
Solution provided.

**Comment by dficarel** [comment]
Thank You Tim for the prompt fix.

Dom

**Comment by timahenning** [comment]
You are welcome.  Thank Jitendra.  @shirolkar He fixed it.

Tim
